name: Build and Deploy

on:
  push:
    branches:
      - main # å½“masteråˆ†æ”¯æœ‰å˜æ›´ï¼Œåˆ™æ‰§è¡Œä»¥ä¸‹jobsæ“ä½œ

env:
  TARGET: gh-page # éƒ¨ç½²åˆ†æ”¯

jobs:
  deploying_shopify_vite_project:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.1
        
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          # Version of pnpm to install
          version: latest

      - name: building
        run: |
          pnpm install
          pnpm run vite:build

      - name: Deploy ğŸš€
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: ${{ env.TARGET }}
